services:
  nest-app:
    build:
      context: ./back-ouvidoria
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # volumes:
    #   - ./project/src:/usr/src/app/src
    #   - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    develop:
      watch:
          - action: sync
            path: ./back-ouvidoria/src
            target: /usr/src/app/src
          - action: rebuild
            path: ./back-ouvidoria/package.json
  
#   db:
#     image: postgres:16
#     container_name: postgres_db
#     restart: unless-stopped
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: root
#       POSTGRES_DB: mydatabase
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data: