services:
  nest-app:
    build:
      context: ./back-ouvidoria
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres_db
    networks:
      - default
    develop:
      watch:
          - action: sync
            path: ./back-ouvidoria/
            target: /usr/src/app/
            ignore:
              - node_modules
              - .git
              - .idea
              - .vscode
              - dist
          - action: rebuild
            path: ./back-ouvidoria/package.json
    env_file:
      - ./back.env

  front-app:
    build:
      context: ./front-ouvidoria
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - nest-app
    networks:
      - default
    env_file:
      - ./front.env

  postgres_db:
    image: postgres:latest
    env_file:
      - ./database.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  postgres_data: