services:
  nest-app:
    build:
      context: ./back-ouvidoria
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # volumes:
    #   - ./project/src:/usr/src/app/src
    #   - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres_db
    networks:
      - default
    develop:
      watch:
          - action: sync
            path: ./back-ouvidoria/
            target: /usr/src/app/
            ignore:
              - node_modules
              - .git
              - .idea
              - .vscode
              - dist
          - action: rebuild
            path: ./back-ouvidoria/package.json
  
  postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres       # Garanta que esse usuário existe
      POSTGRES_PASSWORD: senha123   # Senha definida
      POSTGRES_DB: ouvidoria        # Banco de dados padrão
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  postgres_data: